# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FrontendDriverInterface.Api.EmailVerificationRecipe do
  @moduledoc """
  API calls for all endpoints tagged `EmailVerificationRecipe`.
  """

  alias FrontendDriverInterface.Connection
  import FrontendDriverInterface.RequestBuilder


  @doc """
  Check if an email is verified 

  ## Parameters

  - connection (FrontendDriverInterface.Connection): Connection to server
  - api_base_path (String.t): Its value depends on the apiBasePath set by the user
  - s_access_token (String.t): 
  - s_id_refresh_token (String.t): 
  - opts (KeywordList): [optional] Optional parameters
    - :rid (String.t): 
    - :anti_csrf (String.t): This will only be here if enabled by the user.
  ## Returns

  {:ok, FrontendDriverInterface.Model.InlineResponse20012.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec get_verify_email(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, FrontendDriverInterface.Model.InlineResponse20012.t} | {:ok, FrontendDriverInterface.Model.InternalError.t} | {:ok, FrontendDriverInterface.Model.NotFound.t} | {:error, Tesla.Env.t}
  def get_verify_email(connection, api_base_path, s_access_token, s_id_refresh_token, opts \\ []) do
    optional_params = %{
      :"rid" => :headers,
      :"anti-csrf" => :headers
    }
    %{}
    |> method(:get)
    |> url("/#{api_base_path}/user/email/verify")
    |> add_param(, :"sAccessToken", s_access_token)
    |> add_param(, :"sIdRefreshToken", s_id_refresh_token)
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %FrontendDriverInterface.Model.InlineResponse20012{}},
      { 404, %FrontendDriverInterface.Model.NotFound{}},
      { 500, %FrontendDriverInterface.Model.InternalError{}}
    ])
  end

  @doc """
  Verify an email 

  ## Parameters

  - connection (FrontendDriverInterface.Connection): Connection to server
  - api_base_path (String.t): Its value depends on the apiBasePath set by the user
  - opts (KeywordList): [optional] Optional parameters
    - :rid (String.t): 
    - :body (EmailVerifyBody): 
  ## Returns

  {:ok, FrontendDriverInterface.Model.InlineResponse20013.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec verify_email(Tesla.Env.client, String.t, keyword()) :: {:ok, FrontendDriverInterface.Model.InlineResponse20013.t} | {:ok, FrontendDriverInterface.Model.InternalError.t} | {:ok, FrontendDriverInterface.Model.NotFound.t} | {:error, Tesla.Env.t}
  def verify_email(connection, api_base_path, opts \\ []) do
    optional_params = %{
      :"rid" => :headers,
      :body => :body
    }
    %{}
    |> method(:post)
    |> url("/#{api_base_path}/user/email/verify")
    |> add_optional_params(optional_params, opts)
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %FrontendDriverInterface.Model.InlineResponse20013{}},
      { 404, %FrontendDriverInterface.Model.NotFound{}},
      { 500, %FrontendDriverInterface.Model.InternalError{}}
    ])
  end

  @doc """
  Send email verification email 

  ## Parameters

  - connection (FrontendDriverInterface.Connection): Connection to server
  - api_base_path (String.t): Its value depends on the apiBasePath set by the user
  - s_access_token (String.t): 
  - s_id_refresh_token (String.t): 
  - opts (KeywordList): [optional] Optional parameters
    - :rid (String.t): 
    - :anti_csrf (String.t): This will only be here if enabled by the user.
  ## Returns

  {:ok, FrontendDriverInterface.Model.InlineResponse20011.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec verify_email_token(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, FrontendDriverInterface.Model.InlineResponse20011.t} | {:ok, FrontendDriverInterface.Model.InternalError.t} | {:ok, FrontendDriverInterface.Model.NotFound.t} | {:error, Tesla.Env.t}
  def verify_email_token(connection, api_base_path, s_access_token, s_id_refresh_token, opts \\ []) do
    optional_params = %{
      :"rid" => :headers,
      :"anti-csrf" => :headers
    }
    %{}
    |> method(:post)
    |> url("/#{api_base_path}/user/email/verify/token")
    |> add_param(, :"sAccessToken", s_access_token)
    |> add_param(, :"sIdRefreshToken", s_id_refresh_token)
    |> add_optional_params(optional_params, opts)
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %FrontendDriverInterface.Model.InlineResponse20011{}},
      { 404, %FrontendDriverInterface.Model.NotFound{}},
      { 500, %FrontendDriverInterface.Model.InternalError{}}
    ])
  end
end
