# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FrontendDriverInterface.Api.ThirdPartyRecipe do
  @moduledoc """
  API calls for all endpoints tagged `ThirdPartyRecipe`.
  """

  alias FrontendDriverInterface.Connection
  import FrontendDriverInterface.RequestBuilder


  @doc """
  Signin/up a user 

  ## Parameters

  - connection (FrontendDriverInterface.Connection): Connection to server
  - api_base_path (String.t): Its value depends on the apiBasePath set by the user
  - opts (KeywordList): [optional] Optional parameters
    - :rid (String.t): 
    - :third_party_id (String.t): 
  ## Returns

  {:ok, FrontendDriverInterface.Model.InlineResponse2005.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec authorisation_url(Tesla.Env.client, String.t, keyword()) :: {:ok, FrontendDriverInterface.Model.InternalError.t} | {:ok, FrontendDriverInterface.Model.InlineResponse2005.t} | {:ok, FrontendDriverInterface.Model.NotFound.t} | {:error, Tesla.Env.t}
  def authorisation_url(connection, api_base_path, opts \\ []) do
    optional_params = %{
      :"rid" => :headers,
      :"thirdPartyId" => :query
    }
    %{}
    |> method(:get)
    |> url("/#{api_base_path}/authorisationurl")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %FrontendDriverInterface.Model.InlineResponse2005{}},
      { 404, %FrontendDriverInterface.Model.NotFound{}},
      { 500, %FrontendDriverInterface.Model.InternalError{}}
    ])
  end

  @doc """
  Signin/up a user 

  ## Parameters

  - connection (FrontendDriverInterface.Connection): Connection to server
  - api_base_path (String.t): Its value depends on the apiBasePath set by the user
  - opts (KeywordList): [optional] Optional parameters
    - :rid (String.t): 
    - :body (ApiBasePathSigninupBody1): Should contain one of code or authCodeResponse, clientId is optional
  ## Returns

  {:ok, FrontendDriverInterface.Model.InlineResponse2004.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec sign_in_up(Tesla.Env.client, String.t, keyword()) :: {:ok, FrontendDriverInterface.Model.InternalError.t} | {:ok, FrontendDriverInterface.Model.InlineResponse2004.t} | {:ok, FrontendDriverInterface.Model.NotFound.t} | {:error, Tesla.Env.t}
  def sign_in_up(connection, api_base_path, opts \\ []) do
    optional_params = %{
      :"rid" => :headers,
      :body => :body
    }
    %{}
    |> method(:post)
    |> url("/#{api_base_path}/signinup")
    |> add_optional_params(optional_params, opts)
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %FrontendDriverInterface.Model.InlineResponse2004{}},
      { 404, %FrontendDriverInterface.Model.NotFound{}},
      { 500, %FrontendDriverInterface.Model.InternalError{}}
    ])
  end

  @doc """
  Handles sign in with the apple. 

  ## Parameters

  - connection (FrontendDriverInterface.Connection): Connection to server
  - api_base_path (String.t): Its value depends on the apiBasePath set by the user
  - opts (KeywordList): [optional] Optional parameters
    - :code (String.t): The Authorization code which will be exchanged for an access token
    - :state (String.t): A unique string used to mitigate CSRF attacks
  ## Returns

  {:ok, nil} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec third_party_callback_apple(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, FrontendDriverInterface.Model.InternalError.t} | {:ok, FrontendDriverInterface.Model.NotFound.t} | {:error, Tesla.Env.t}
  def third_party_callback_apple(connection, api_base_path, opts \\ []) do
    optional_params = %{
      :"code" => :form,
      :"state" => :form
    }
    %{}
    |> method(:post)
    |> url("/#{api_base_path}/callback/apple")
    |> add_optional_params(optional_params, opts)
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, false},
      { 404, %FrontendDriverInterface.Model.NotFound{}},
      { 500, %FrontendDriverInterface.Model.InternalError{}}
    ])
  end
end
