# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FrontendDriverInterface.Model.ApiBasePathSigninupBody1 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"redirectURI",
    :"thirdPartyId",
    :"code",
    :"authCodeResponse",
    :"clientId"
  ]

  @type t :: %__MODULE__{
    :"redirectURI" => String.t | nil,
    :"thirdPartyId" => String.t | nil,
    :"code" => String.t | nil,
    :"authCodeResponse" => FrontendDriverInterface.Model.AuthCodeResponse.t | nil,
    :"clientId" => String.t | nil
  }
end

defimpl Poison.Decoder, for: FrontendDriverInterface.Model.ApiBasePathSigninupBody1 do
  import FrontendDriverInterface.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"authCodeResponse", :struct, FrontendDriverInterface.Model.AuthCodeResponse, options)
  end
end

