# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FrontendDriverInterface.Model.CodeResendBody do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"deviceId",
    :"preAuthSessionId"
  ]

  @type t :: %__MODULE__{
    :"deviceId" => String.t,
    :"preAuthSessionId" => String.t
  }
end

defimpl Poison.Decoder, for: FrontendDriverInterface.Model.CodeResendBody do
  def decode(value, _options) do
    value
  end
end

