# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FrontendDriverInterface.Model.CodeConsumeBodyOneOf do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"preAuthSessionId",
    :"linkCode"
  ]

  @type t :: %__MODULE__{
    :"preAuthSessionId" => String.t,
    :"linkCode" => String.t
  }
end

defimpl Poison.Decoder, for: FrontendDriverInterface.Model.CodeConsumeBodyOneOf do
  def decode(value, _options) do
    value
  end
end

