# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FrontendDriverInterface.Model.EmailVerifyBody do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"method",
    :"token"
  ]

  @type t :: %__MODULE__{
    :"method" => String.t | nil,
    :"token" => String.t | nil
  }
end

defimpl Poison.Decoder, for: FrontendDriverInterface.Model.EmailVerifyBody do
  def decode(value, _options) do
    value
  end
end

