# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FrontendDriverInterface.Model.FieldErrorResponseFormFields do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"error"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"error" => String.t | nil
  }
end

defimpl Poison.Decoder, for: FrontendDriverInterface.Model.FieldErrorResponseFormFields do
  def decode(value, _options) do
    value
  end
end

