# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FrontendDriverInterface.Model.FormFieldsInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"value"
  ]

  @type t :: %__MODULE__{
    :"id" => FrontendDriverInterface.Model.Id.t | nil,
    :"value" => String.t | nil
  }
end

defimpl Poison.Decoder, for: FrontendDriverInterface.Model.FormFieldsInner do
  import FrontendDriverInterface.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"id", :struct, FrontendDriverInterface.Model.Id, options)
  end
end

