# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FrontendDriverInterface.Model.InlineResponse20014Keys do
  @moduledoc """
  A JWK that can be used to verify a JWT
  """

  @derive [Poison.Encoder]
  defstruct [
    :"alg",
    :"kty",
    :"use",
    :"kid",
    :"n",
    :"e"
  ]

  @type t :: %__MODULE__{
    :"alg" => String.t | nil,
    :"kty" => String.t | nil,
    :"use" => String.t | nil,
    :"kid" => String.t | nil,
    :"n" => String.t | nil,
    :"e" => String.t | nil
  }
end

defimpl Poison.Decoder, for: FrontendDriverInterface.Model.InlineResponse20014Keys do
  def decode(value, _options) do
    value
  end
end

