# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FrontendDriverInterface.Model.InlineResponse2004 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"status",
    :"user",
    :"createdNewUser",
    :"message"
  ]

  @type t :: %__MODULE__{
    :"status" => String.t | nil,
    :"user" => FrontendDriverInterface.Model.ThirdPartyUser.t | nil,
    :"createdNewUser" => boolean() | nil,
    :"message" => String.t | nil
  }
end

defimpl Poison.Decoder, for: FrontendDriverInterface.Model.InlineResponse2004 do
  import FrontendDriverInterface.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"user", :struct, FrontendDriverInterface.Model.ThirdPartyUser, options)
  end
end

