# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FrontendDriverInterface.Model.InlineResponse20012OneOf do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"status",
    :"isVerified"
  ]

  @type t :: %__MODULE__{
    :"status" => FrontendDriverInterface.Model.StatusOk.t | nil,
    :"isVerified" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: FrontendDriverInterface.Model.InlineResponse20012OneOf do
  import FrontendDriverInterface.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"status", :struct, FrontendDriverInterface.Model.StatusOk, options)
  end
end

