# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FrontendDriverInterface.Model.PasswordResetBody1 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"method",
    :"formfields",
    :"token"
  ]

  @type t :: %__MODULE__{
    :"method" => String.t | nil,
    :"formfields" => [FrontendDriverInterface.Model.FormFieldsInner.t] | nil,
    :"token" => String.t | nil
  }
end

defimpl Poison.Decoder, for: FrontendDriverInterface.Model.PasswordResetBody1 do
  import FrontendDriverInterface.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"formfields", :list, FrontendDriverInterface.Model.FormFieldsInner, options)
  end
end

