# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FrontendDriverInterface.Model.PasswordlessUser do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"email",
    :"phoneNumber",
    :"timeJoined"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"email" => String.t | nil,
    :"phoneNumber" => String.t | nil,
    :"timeJoined" => float() | nil
  }
end

defimpl Poison.Decoder, for: FrontendDriverInterface.Model.PasswordlessUser do
  def decode(value, _options) do
    value
  end
end

