# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FrontendDriverInterface.Model.ResetTokenBody1 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"formFields"
  ]

  @type t :: %__MODULE__{
    :"formFields" => [FrontendDriverInterface.Model.FormFieldsInner.t] | nil
  }
end

defimpl Poison.Decoder, for: FrontendDriverInterface.Model.ResetTokenBody1 do
  import FrontendDriverInterface.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"formFields", :list, FrontendDriverInterface.Model.FormFieldsInner, options)
  end
end

