# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FrontendDriverInterface.Model.SigninupCodeBodyOneOf1 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"phoneNumber"
  ]

  @type t :: %__MODULE__{
    :"phoneNumber" => String.t
  }
end

defimpl Poison.Decoder, for: FrontendDriverInterface.Model.SigninupCodeBodyOneOf1 do
  def decode(value, _options) do
    value
  end
end

