# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FrontendDriverInterface.Model.ThirdPartyUser do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"email",
    :"timeJoined",
    :"thirdParty"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"email" => String.t | nil,
    :"timeJoined" => float() | nil,
    :"thirdParty" => FrontendDriverInterface.Model.ThirdPartyUserThirdParty.t | nil
  }
end

defimpl Poison.Decoder, for: FrontendDriverInterface.Model.ThirdPartyUser do
  import FrontendDriverInterface.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"thirdParty", :struct, FrontendDriverInterface.Model.ThirdPartyUserThirdParty, options)
  end
end

